"""Security tests for quarantined auto-generated descriptor handling."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from urllib import request

import pytest

from kaval.discovery.descriptor_generation import AutoGeneratedDescriptorGenerator
from kaval.investigation.local_model import LocalModelConfig, LocalModelResponseError
from kaval.models import Endpoint, EndpointProtocol, Service, ServiceStatus, ServiceType


def test_auto_generated_descriptor_generation_rejects_credential_hints_from_model() -> None:
    """Model output must not smuggle credential hints into quarantined drafts."""

    def transport(http_request: request.Request, timeout_seconds: float) -> bytes:
        del http_request, timeout_seconds
        return json.dumps(
            {
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "id": "custom_app",
                                    "name": "Custom App",
                                    "category": "custom",
                                    "match": {
                                        "image_patterns": ["ghcr.io/example/custom-app*"],
                                        "container_name_patterns": ["custom-app"],
                                    },
                                    "endpoints": {},
                                    "dns_targets": [],
                                    "log_signals": {"errors": [], "warnings": []},
                                    "typical_dependencies": {"containers": [], "shares": []},
                                    "common_failure_modes": [],
                                    "investigation_context": None,
                                    "credential_hints": {
                                        "api_key": {
                                            "description": "Secret",
                                            "location": "Settings",
                                        }
                                    },
                                }
                            )
                        }
                    }
                ]
            }
        ).encode("utf-8")

    generator = AutoGeneratedDescriptorGenerator(
        config=LocalModelConfig(
            base_url="http://localhost:11434",
            model="qwen3:8b",
        ),
        transport=transport,
    )

    with pytest.raises(
        LocalModelResponseError,
        match="invalid descriptor draft",
    ):
        generator.generate(service=build_unmatched_service(), now=ts(10, 0))


def ts(hour: int, minute: int = 0) -> datetime:
    """Build a deterministic UTC timestamp for descriptor-security tests."""
    return datetime(2026, 4, 8, hour, minute, tzinfo=UTC)


def build_unmatched_service() -> Service:
    """Build one unmatched container service for descriptor-security tests."""
    return Service(
        id="svc-custom-app",
        name="custom-app",
        type=ServiceType.CONTAINER,
        category="container",
        status=ServiceStatus.HEALTHY,
        descriptor_id=None,
        descriptor_source=None,
        container_id="container-custom-app",
        vm_id=None,
        image="ghcr.io/example/custom-app:1.0.0",
        endpoints=[
            Endpoint(
                name="port_8080_tcp",
                protocol=EndpointProtocol.TCP,
                host="custom-app",
                port=8080,
                path=None,
                url=None,
                auth_required=False,
                expected_status=None,
            )
        ],
        dns_targets=[],
        dependencies=[],
        dependents=[],
        last_check=ts(9, 0),
        active_findings=0,
        active_incidents=0,
    )
