"""Local-model generation for quarantined auto-generated service descriptors."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum
from fnmatch import fnmatch
from pathlib import Path

from pydantic import Field, ValidationError

from kaval.discovery.descriptors import (
    DescriptorDependencies,
    DescriptorEndpoint,
    DescriptorFailureMode,
    DescriptorLogSignals,
    DescriptorMatchRule,
    ServiceDescriptor,
    descriptor_identifier,
)
from kaval.investigation.local_model import (
    LocalModelConfig,
    LocalModelResponseError,
    RequestTransport,
    request_openai_compatible_json,
)
from kaval.models import DescriptorSource, DnsTarget, Endpoint, JsonValue, KavalModel, Service

_NON_ALNUM_RE = re.compile(r"[^a-z0-9]+")


class DescriptorGenerationError(RuntimeError):
    """Raised when descriptor generation cannot produce a valid candidate."""


class DescriptorGenerationPolicyError(DescriptorGenerationError):
    """Raised when a generated candidate violates quarantine policy."""


class QuarantinedDescriptorReviewState(StrEnum):
    """Visible review states for quarantined descriptor candidates."""

    PENDING = "pending"
    DEFERRED = "deferred"


class QuarantinedDescriptorReviewRecord(KavalModel):
    """Persisted review state for one quarantined descriptor candidate."""

    descriptor_id: str
    review_state: QuarantinedDescriptorReviewState = (
        QuarantinedDescriptorReviewState.PENDING
    )
    updated_at: datetime


class _GeneratedDescriptorDraft(KavalModel):
    """The constrained model payload accepted from the local generator."""

    id: str
    name: str
    category: str
    project_url: str | None = None
    icon: str | None = None
    match: DescriptorMatchRule
    endpoints: dict[str, DescriptorEndpoint] = Field(default_factory=dict)
    dns_targets: list[DnsTarget] = Field(default_factory=list)
    log_signals: DescriptorLogSignals = Field(default_factory=DescriptorLogSignals)
    typical_dependencies: DescriptorDependencies = Field(default_factory=DescriptorDependencies)
    common_failure_modes: list[DescriptorFailureMode] = Field(default_factory=list)
    investigation_context: str | None = None


@dataclass(frozen=True, slots=True)
class AutoGeneratedDescriptorGenerator:
    """Generate quarantined descriptor candidates through the local model path."""

    config: LocalModelConfig
    transport: RequestTransport | None = None

    def generate(self, *, service: Service, now: datetime | None = None) -> ServiceDescriptor:
        """Generate one quarantined descriptor candidate for an unmatched service."""
        effective_now = now or datetime.now(tz=UTC)
        response_payload = request_openai_compatible_json(
            config=self.config,
            system_prompt=_render_system_prompt(),
            user_prompt=_render_user_prompt(service=service, now=effective_now),
            transport=self.transport,
        )
        draft = _parse_generated_descriptor_draft(response_payload)
        descriptor = _finalize_generated_descriptor(
            draft=draft,
            service=service,
            now=effective_now,
        )
        _validate_generated_descriptor_policy(
            service=service,
            descriptor=descriptor,
        )
        return descriptor


def _parse_generated_descriptor_draft(
    response_payload: dict[str, JsonValue],
) -> _GeneratedDescriptorDraft:
    """Parse one model response into the constrained draft shape."""
    try:
        return _GeneratedDescriptorDraft.model_validate(response_payload)
    except ValidationError as exc:
        raise LocalModelResponseError("local model returned an invalid descriptor draft") from exc


def build_quarantined_descriptor_review_state_path(
    services_dir: Path | str,
    *,
    category: str,
    descriptor_id: str,
) -> Path:
    """Return the canonical sidecar path for one review-state record."""
    return (
        Path(services_dir)
        / "auto_generated"
        / ".review_state"
        / category
        / f"{descriptor_id}.json"
    )


def load_quarantined_descriptor_review_record(
    services_dir: Path | str,
    *,
    category: str,
    descriptor_id: str,
) -> QuarantinedDescriptorReviewRecord | None:
    """Load one persisted review-state sidecar when it exists."""
    state_path = build_quarantined_descriptor_review_state_path(
        services_dir,
        category=category,
        descriptor_id=descriptor_id,
    )
    if not state_path.exists():
        return None
    try:
        payload = json.loads(state_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise DescriptorGenerationError(
            f"invalid review state for quarantined descriptor {category}/{descriptor_id}"
        ) from exc
    try:
        return QuarantinedDescriptorReviewRecord.model_validate(payload)
    except ValidationError as exc:
        raise DescriptorGenerationError(
            f"invalid review state for quarantined descriptor {category}/{descriptor_id}"
        ) from exc


def write_quarantined_descriptor_review_record(
    services_dir: Path | str,
    *,
    descriptor: ServiceDescriptor,
    review_state: QuarantinedDescriptorReviewState,
    updated_at: datetime,
) -> QuarantinedDescriptorReviewRecord:
    """Persist one review-state sidecar for a quarantined descriptor candidate."""
    record = QuarantinedDescriptorReviewRecord(
        descriptor_id=descriptor_identifier(descriptor),
        review_state=review_state,
        updated_at=updated_at,
    )
    state_path = build_quarantined_descriptor_review_state_path(
        services_dir,
        category=descriptor.category,
        descriptor_id=descriptor.id,
    )
    state_path.parent.mkdir(parents=True, exist_ok=True)
    state_path.write_text(
        json.dumps(record.model_dump(mode="json"), indent=2, sort_keys=True),
        encoding="utf-8",
    )
    return record


def delete_quarantined_descriptor_review_record(
    services_dir: Path | str,
    *,
    category: str,
    descriptor_id: str,
) -> None:
    """Delete one persisted review-state sidecar when it exists."""
    state_path = build_quarantined_descriptor_review_state_path(
        services_dir,
        category=category,
        descriptor_id=descriptor_id,
    )
    if state_path.exists():
        state_path.unlink()


def _finalize_generated_descriptor(
    *,
    draft: _GeneratedDescriptorDraft,
    service: Service,
    now: datetime,
) -> ServiceDescriptor:
    """Normalize one model draft into the quarantined on-disk descriptor contract."""
    fallback_id = _fallback_descriptor_id(service)
    descriptor_id = _slugify_segment(draft.id, fallback=fallback_id)
    descriptor_category = _slugify_segment(draft.category, fallback="custom")
    descriptor_name = draft.name.strip() or service.name
    return ServiceDescriptor(
        id=descriptor_id,
        name=descriptor_name,
        category=descriptor_category,
        project_url=draft.project_url,
        icon=draft.icon,
        match=draft.match,
        endpoints=draft.endpoints,
        dns_targets=draft.dns_targets,
        log_signals=draft.log_signals,
        typical_dependencies=draft.typical_dependencies,
        common_failure_modes=draft.common_failure_modes,
        investigation_context=draft.investigation_context,
        source=DescriptorSource.AUTO_GENERATED,
        verified=False,
        generated_at=now,
    )


def _validate_generated_descriptor_policy(
    *,
    service: Service,
    descriptor: ServiceDescriptor,
) -> None:
    """Enforce the quarantined auto-generated descriptor policy."""
    validate_quarantined_descriptor_policy(descriptor)
    if not _service_matches_descriptor(service=service, descriptor=descriptor):
        raise DescriptorGenerationPolicyError(
            "generated descriptor candidate does not match the current service metadata"
        )


def validate_quarantined_descriptor_policy(descriptor: ServiceDescriptor) -> None:
    """Enforce the shared quarantine policy for auto-generated descriptors."""
    if descriptor.source is not DescriptorSource.AUTO_GENERATED:
        raise DescriptorGenerationPolicyError(
            "generated descriptor candidate must keep source=auto_generated"
        )
    if descriptor.verified:
        raise DescriptorGenerationPolicyError(
            "generated descriptor candidate must keep verified=false"
        )
    if descriptor.generated_at is None:
        raise DescriptorGenerationPolicyError(
            "generated descriptor candidate must record generated_at"
        )
    if descriptor.credential_hints:
        raise DescriptorGenerationPolicyError(
            "generated descriptor candidate must not include credential hints"
        )
    if descriptor.inspection.surfaces:
        raise DescriptorGenerationPolicyError(
            "generated descriptor candidate must not include inspection surfaces"
        )


def _service_matches_descriptor(*, service: Service, descriptor: ServiceDescriptor) -> bool:
    """Return whether one descriptor candidate matches the current unmatched service."""
    image_matches = (
        service.image is not None
        and any(fnmatch(service.image, pattern) for pattern in descriptor.match.image_patterns)
    )
    name_aliases = {
        service.name.casefold(),
        service.id.removeprefix("svc-").casefold(),
    }
    name_matches = any(
        fnmatch(name_alias, pattern.casefold())
        for name_alias in name_aliases
        for pattern in descriptor.match.container_name_patterns
    )
    return image_matches or name_matches


def _fallback_descriptor_id(service: Service) -> str:
    """Return a deterministic fallback identifier from the current service metadata."""
    image_name = (service.image or "").split("/")[-1]
    image_basename = image_name.split(":", maxsplit=1)[0]
    candidate = image_basename or service.name or service.id
    return _slugify_segment(candidate, fallback="generated_service")


def _slugify_segment(value: str, *, fallback: str) -> str:
    """Normalize descriptor ids and categories into stable path-safe tokens."""
    normalized = _NON_ALNUM_RE.sub("_", value.casefold()).strip("_")
    return normalized or fallback


def _render_system_prompt() -> str:
    """Render the fixed system prompt for descriptor generation."""
    return (
        "You generate Kaval service descriptor drafts for one unmatched container. "
        "Return a single JSON object only. Use conservative, review-friendly values. "
        "The response must include only these top-level fields: "
        "id, name, category, project_url, icon, match, endpoints, dns_targets, "
        "log_signals, typical_dependencies, common_failure_modes, investigation_context. "
        "Use lowercase snake_case for id and category. "
        "Ensure at least one match pattern matches the current service image or name. "
        "Do not include credential_hints, inspection, source, verified, generated_at, "
        "markdown, or any explanatory text."
    )


def _render_user_prompt(*, service: Service, now: datetime) -> str:
    """Render the current unmatched-service metadata for the local model."""
    payload = {
        "generated_at": now.isoformat(),
        "service_id": service.id,
        "service_name": service.name,
        "service_type": service.type.value,
        "service_category": service.category,
        "service_status": service.status.value,
        "container_id": service.container_id,
        "image": service.image,
        "endpoints": [_endpoint_payload(endpoint) for endpoint in service.endpoints],
    }
    return (
        "Generate a conservative quarantined service descriptor candidate for this "
        "currently unmatched service:\n"
        + json.dumps(payload, indent=2, sort_keys=False)
    )


def _endpoint_payload(endpoint: Endpoint) -> dict[str, JsonValue]:
    """Render one current endpoint into prompt-safe JSON."""
    return {
        "name": endpoint.name,
        "protocol": endpoint.protocol.value,
        "host": endpoint.host,
        "port": endpoint.port,
        "path": endpoint.path,
        "auth_required": endpoint.auth_required,
        "expected_status": endpoint.expected_status,
    }
