"""Unit tests for quarantined auto-generated descriptor generation."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import cast
from urllib import request

import pytest

from kaval.discovery.descriptor_generation import (
    AutoGeneratedDescriptorGenerator,
    DescriptorGenerationPolicyError,
    QuarantinedDescriptorReviewState,
    load_quarantined_descriptor_review_record,
    write_quarantined_descriptor_review_record,
)
from kaval.investigation.local_model import LocalModelConfig
from kaval.models import Endpoint, EndpointProtocol, Service, ServiceStatus, ServiceType


def ts(hour: int, minute: int = 0) -> datetime:
    """Build a deterministic UTC timestamp for descriptor-generation tests."""
    return datetime(2026, 4, 8, hour, minute, tzinfo=UTC)


def test_auto_generated_descriptor_generator_returns_quarantined_candidate() -> None:
    """The generator should normalize one local-model draft into a quarantined descriptor."""
    captured_request: dict[str, object] = {}

    def transport(http_request: request.Request, timeout_seconds: float) -> bytes:
        body = json.loads(cast(bytes, http_request.data).decode("utf-8"))
        captured_request["url"] = http_request.full_url
        captured_request["timeout"] = timeout_seconds
        captured_request["body"] = body
        return json.dumps(
            {
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "id": "Custom App",
                                    "name": "Custom App",
                                    "category": "Media Tools",
                                    "project_url": "https://example.test/custom-app",
                                    "icon": "custom-app.svg",
                                    "match": {
                                        "image_patterns": [
                                            "ghcr.io/example/custom-app*"
                                        ],
                                        "container_name_patterns": ["custom-app"],
                                    },
                                    "endpoints": {
                                        "web_ui": {
                                            "port": 8080,
                                            "path": "/",
                                        }
                                    },
                                    "dns_targets": [],
                                    "log_signals": {
                                        "errors": ["Connection refused"],
                                        "warnings": [],
                                    },
                                    "typical_dependencies": {
                                        "containers": ["postgres"],
                                        "shares": ["media"],
                                    },
                                    "common_failure_modes": [],
                                    "investigation_context": (
                                        "This service exposes a web UI on 8080."
                                    ),
                                }
                            )
                        }
                    }
                ]
            }
        ).encode("utf-8")

    generator = AutoGeneratedDescriptorGenerator(
        config=LocalModelConfig(
            base_url="http://localhost:11434",
            model="qwen3:8b",
            timeout_seconds=12.0,
        ),
        transport=transport,
    )

    descriptor = generator.generate(service=build_unmatched_service(), now=ts(9, 30))

    assert captured_request["url"] == "http://localhost:11434/v1/chat/completions"
    assert captured_request["timeout"] == 12.0
    body = cast(dict[str, object], captured_request["body"])
    assert body["model"] == "qwen3:8b"
    assert descriptor.id == "custom_app"
    assert descriptor.category == "media_tools"
    assert descriptor.source == "auto_generated"
    assert descriptor.verified is False
    assert descriptor.generated_at == ts(9, 30)
    assert descriptor.inspection.surfaces == []
    assert descriptor.credential_hints == {}
    assert descriptor.match.image_patterns == ["ghcr.io/example/custom-app*"]


def test_auto_generated_descriptor_generator_rejects_non_matching_draft() -> None:
    """The generator should reject drafts that would not match the current service."""

    def transport(http_request: request.Request, timeout_seconds: float) -> bytes:
        del http_request, timeout_seconds
        return json.dumps(
            {
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "id": "wrong_app",
                                    "name": "Wrong App",
                                    "category": "custom",
                                    "match": {
                                        "image_patterns": ["ghcr.io/example/other-app*"],
                                        "container_name_patterns": ["other-app"],
                                    },
                                    "endpoints": {},
                                    "dns_targets": [],
                                    "log_signals": {"errors": [], "warnings": []},
                                    "typical_dependencies": {"containers": [], "shares": []},
                                    "common_failure_modes": [],
                                    "investigation_context": None,
                                }
                            )
                        }
                    }
                ]
            }
        ).encode("utf-8")

    generator = AutoGeneratedDescriptorGenerator(
        config=LocalModelConfig(
            base_url="http://localhost:11434",
            model="qwen3:8b",
        ),
        transport=transport,
    )

    with pytest.raises(
        DescriptorGenerationPolicyError,
        match="does not match the current service metadata",
    ):
        generator.generate(service=build_unmatched_service(), now=ts(9, 45))


def test_quarantined_descriptor_review_record_round_trips(tmp_path) -> None:
    """Deferred review state should persist in the quarantine sidecar tree."""
    service = build_unmatched_service()
    generator = AutoGeneratedDescriptorGenerator(
        config=LocalModelConfig(
            base_url="http://localhost:11434",
            model="qwen3:8b",
        ),
        transport=lambda http_request, timeout_seconds: json.dumps(
            {
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "id": "custom_app",
                                    "name": "Custom App",
                                    "category": "custom",
                                    "match": {
                                        "image_patterns": ["ghcr.io/example/custom-app*"],
                                        "container_name_patterns": ["custom-app"],
                                    },
                                    "endpoints": {},
                                    "dns_targets": [],
                                    "log_signals": {"errors": [], "warnings": []},
                                    "typical_dependencies": {
                                        "containers": [],
                                        "shares": [],
                                    },
                                    "common_failure_modes": [],
                                    "investigation_context": None,
                                }
                            )
                        }
                    }
                ]
            }
        ).encode("utf-8"),
    )
    descriptor = generator.generate(service=service, now=ts(10, 0))

    written = write_quarantined_descriptor_review_record(
        tmp_path,
        descriptor=descriptor,
        review_state=QuarantinedDescriptorReviewState.DEFERRED,
        updated_at=ts(10, 5),
    )
    loaded = load_quarantined_descriptor_review_record(
        tmp_path,
        category=descriptor.category,
        descriptor_id=descriptor.id,
    )

    assert written.review_state is QuarantinedDescriptorReviewState.DEFERRED
    assert loaded is not None
    assert loaded.review_state is QuarantinedDescriptorReviewState.DEFERRED
    assert loaded.updated_at == ts(10, 5)


def build_unmatched_service() -> Service:
    """Build one unmatched container service for descriptor-generation tests."""
    return Service(
        id="svc-custom-app",
        name="custom-app",
        type=ServiceType.CONTAINER,
        category="container",
        status=ServiceStatus.HEALTHY,
        descriptor_id=None,
        descriptor_source=None,
        container_id="container-custom-app",
        vm_id=None,
        image="ghcr.io/example/custom-app:1.0.0",
        endpoints=[
            Endpoint(
                name="port_8080_tcp",
                protocol=EndpointProtocol.TCP,
                host="custom-app",
                port=8080,
                path=None,
                url=None,
                auth_required=False,
                expected_status=None,
            )
        ],
        dns_targets=[],
        dependencies=[],
        dependents=[],
        last_check=ts(9, 0),
        active_findings=0,
        active_incidents=0,
    )
