"""External API integration package."""

from kaval.integrations.external_apis.dockerhub import (
    DockerHubClient,
    DockerHubClientConfig,
    DockerHubError,
    DockerHubImageReference,
    DockerHubNotFoundError,
    DockerHubOfflineError,
    DockerHubRepository,
    DockerHubResponseError,
    DockerHubTag,
    DockerHubTagFeed,
    DockerHubTagImage,
    DockerHubTransportError,
    decode_repository_payload,
    decode_tag_payload,
    parse_dockerhub_reference,
)
from kaval.integrations.external_apis.github_releases import (
    GitHubRelease,
    GitHubReleaseFeed,
    GitHubReleasesClient,
    GitHubReleasesClientConfig,
    GitHubReleasesError,
    GitHubReleasesNotFoundError,
    GitHubReleasesOfflineError,
    GitHubReleasesResponseError,
    GitHubReleasesTransportError,
    GitHubRepositoryReference,
    decode_release_payload,
    parse_repository_reference,
)

__all__ = [
    "DockerHubClient",
    "DockerHubClientConfig",
    "DockerHubError",
    "DockerHubImageReference",
    "DockerHubNotFoundError",
    "DockerHubOfflineError",
    "DockerHubRepository",
    "DockerHubResponseError",
    "DockerHubTag",
    "DockerHubTagFeed",
    "DockerHubTagImage",
    "DockerHubTransportError",
    "GitHubRelease",
    "GitHubReleaseFeed",
    "GitHubReleasesClient",
    "GitHubReleasesClientConfig",
    "GitHubReleasesError",
    "GitHubReleasesNotFoundError",
    "GitHubReleasesOfflineError",
    "GitHubReleasesResponseError",
    "GitHubReleasesTransportError",
    "GitHubRepositoryReference",
    "decode_repository_payload",
    "decode_tag_payload",
    "decode_release_payload",
    "parse_dockerhub_reference",
    "parse_repository_reference",
]
